Repository FRONTENDBOOTCAMP-14th/js_project_team_4, pull requests merged in 2025-07, with the labels that each got.

#12 task: 날씨 아이콘 및 날씨 배경 이미지 추가
  public/img/bg/clear.jpg
  public/img/bg/clouds-night.jpg
  public/img/bg/clouds.jpg
  public/img/bg/mist.jpg
  public/img/bg/night.jpg
  public/img/bg/rain.jpg
  public/img/bg/snow.jpg
  public/img/bg/thunderstorm.jpg
  public/img/icons/01d.svg
  public/img/icons/01n.svg
  public/img/icons/02d.svg
  public/img/icons/02n.svg
  public/img/icons/03d.svg
  public/img/icons/03n.svg
  public/img/icons/04d.svg
  public/img/icons/04n.svg
  public/img/icons/09d.svg
  public/img/icons/09n.svg
  public/img/icons/10d.svg
  public/img/icons/10n.svg
  public/img/icons/11d.svg
  public/img/icons/11n.svg
  public/img/icons/13d.svg
  public/img/icons/13n.svg
  public/img/icons/50d.svg
  public/img/icons/50n.svg
  public/img/icons/close.svg
  public/img/icons/cloudy.svg
  public/img/icons/humadity.svg
  public/img/icons/search.svg
  public/img/icons/temp-max.svg
  public/img/icons/temp-min.svg
  public/img/icons/wind.svg
Labels: 안동원

#18 Feature/todo list updata/lee - TODO-List 컴포넌트 완성
  src/components/todolist.html
  src/scripts/todolist.js
  src/styles/components/todolist.css
Labels: 개선사항

#25 feat: todo-list indexed api 연결
  src/scripts/todolist.js
Labels: 개선사항, 이성은

#33 Feature/search bar style/lee - 검색바 컴포넌트 조정
  src/components/searchbar.html
  src/styles/components/searchbar.css
Labels: 개선사항, 이성은

#56 Refactor/search bar/lee - 검색바 조정
  src/components/searchbar.html
  src/scripts/searchbar.js
  src/styles/components/searchbar.css
Labels: 개선사항, 이성은

#65 refactor/search bar/lee - 기본 색상 설정값 변경
  src/components/searchbar.html
  src/pages/home.html
  src/styles/components/searchbar.css
Labels: 개선사항, 이성은

#78 Feature/dino/lee - 공룡 게임 컴포넌트 추가
  index.html
  public/img/dinosour/cactus.png
  public/img/dinosour/dinosour-fail.png
  public/img/dinosour/dinosour-jump.png
  public/img/dinosour/dinosour-run1.png
  public/img/dinosour/dinosour-run2.png
  public/img/dinosour/dinosour.png
  public/img/dinosour/gamestart-black.svg
  public/img/dinosour/gamestart-white.svg
  src/components/dino.html
  src/pages/home.html
  src/scripts/dino.js
  src/styles/app.css
  src/styles/components/dino.css
  src/styles/components/index.css
Labels: 개선사항, 이성은
